// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3IXO6F3CfSxpJzwgi9cLXih6PLswwuP4',
    appId: '1:393831943:web:3d0192bc1e331df383aca2',
    messagingSenderId: '393831943',
    projectId: 'medicalland-5f8dc',
    // authDomain: 'localhost',
    authDomain: 'medicalland-5f8dc.firebaseapp.com',
    storageBucket: 'medicalland-5f8dc.firebasestorage.app',
    measurementId: 'G-D1XRWXFSPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7mphPzY1LvD7cSND2kUsnX2mD47ZabE',
    appId: '1:393831943:android:12f25bda7d44d13183aca2',
    messagingSenderId: '393831943',
    projectId: 'medicalland-5f8dc',
    storageBucket: 'medicalland-5f8dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzXurIijSpj5Z2MC7b5j7LwejTMHFnv0',
    appId: '1:393831943:ios:895f62d8fa64cd8083aca2',
    messagingSenderId: '393831943',
    projectId: 'medicalland-5f8dc',
    storageBucket: 'medicalland-5f8dc.firebasestorage.app',
    iosBundleId: 'com.example.companyWebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzzXurIijSpj5Z2MC7b5j7LwejTMHFnv0',
    appId: '1:393831943:ios:895f62d8fa64cd8083aca2',
    messagingSenderId: '393831943',
    projectId: 'medicalland-5f8dc',
    storageBucket: 'medicalland-5f8dc.firebasestorage.app',
    iosBundleId: 'com.example.companyWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3IXO6F3CfSxpJzwgi9cLXih6PLswwuP4',
    appId: '1:393831943:web:e2cff8be26eb6bdc83aca2',
    messagingSenderId: '393831943',
    projectId: 'medicalland-5f8dc',
    authDomain: 'medicalland-5f8dc.firebaseapp.com',
    storageBucket: 'medicalland-5f8dc.firebasestorage.app',
    measurementId: 'G-S0R6FC1MLY',
  );

}